@startuml settlementInitiationErrorCases
skinparam activityFontSize 4
skinparam activityDiamondFontSize 30
skinparam activityArrowFontSize 24
skinparam defaultFontSize 24
skinparam noteFontSize 24
skinparam monochrome true
autonumber

title Settlement Process

actor "Business Hub Operator User" as bu

participant "Settlement Bank" as sbank
participant "Micro-frontend" as ui
participant "Experience Layer" as el
participant "Process Layer" as pl
participant "Report API" as report
participant "Mojaloop" as moja


== Initiate Settlement ==
bu->ui: Initiate Settlement for these windows & Currency

note left
List of Settlement windows Ids
[Optional] Currency or Settlement Model
end note

ui->el: POST: /settlements:initiate 
note left
{"settlementWindows": [
    {
      "id": 0
    }], #settlement window id's (integer)
 "settlementModel":"defered net", # (string)
 "currency", :"XXX" # (currencyEnum)
 }
end note
el->pl: POST: /settlements:initiate
note left
{"settlementWindows": [
    {
      "id": 0
    }], #settlement window id's (integer)
 "settlementModel":"defered net", # (string)
 "currency", :"XXX" # (currencyEnum)
 "user": "hub operators name" # (string) 
 }
end note
group determine settlement Model/s 
pl->moja: Load currencies for windows using GET central-settlements/settlementWindows/{id}
pl->moja: Load settlement models using GET central-ledger/settlementModels 
pl->pl: Determine minimum list of settlement models
end

loop for settlement models
pl->moja: Create settlement \n **POST: central-settlements/settlements** \n{settlementModel, settlementWindowIds[]}
pl->moja: Advance settlement participant account\n state to PS_TRANSFERS_RECORDED \n **PUT: central-settlements/settlements/{id}**
note right moja
**Net credit** participant 
position ledgers are adjusted
end note
end loop

alt Success
pl-->el: Return response, sucess HTTP:200
note right
 {
   [
     "SettlementModel":"defered-net" #(string)
     "id":null, # optional (integer)
     "state": "state" # optional (string)
 }
end note
else Error
 pl-->el: Return Error HTTP: code

note right
 {
   [
     "SettlementModel":"defered-net" #(string)
     "id":null, # optional (integer)
     "state": "state" # optional (string)
     "errorInformation": { # optional
        "errorCode": 0,
        "errorDescription": "string",
        "extensionList": {
          "extension": [
            {
              "key": "string",
              "value": "string" } ] } }
    ]
 }

end note
end

el-->ui: Update UI with settlement status
@enduml